#version: "3"
#
#services:
#  mysql-container:
#    image: mysql
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - spring.liquibase.url=jdbc:mysql://localhost:3306/scholarship
#      - spring.liquibase.user=root
#      - spring.liquibase.password=root
#    volumes:
#      - ./mysql:/docker-entrypoint-initdb.d:ro
#
#  app-container:
#    build:
#      context: ../../../../
#      dockerfile: ./src/main/resources/docker/Dockerfile
#    ports:
#      - 8080:8080
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/scholarship?useSSL=false
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#    depends_on:
#      - mysql-container